### ISSUE TITLE
lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

### ISSUE THREAD

**Issue by WouterSioen** [sumocoders/Framework#115]
during npm install:

`npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0`

**Comment by mathiashelin** [comment]
lodash is a dependency of a node_module we use, we can't force this one to update. I've update all depenencies in https://github.com/sumocoders/Framework/pull/117 but lodash still isn't updated. This issue can be closed if you ask me.
