### ISSUE TITLE
Change the paginator bundle

### ISSUE THREAD

**Issue by StijnVrolijk** [sumocoders/Framework#146]
Currently, we use the KnpPaginator bundle, this is okay for simple pagination but lacks in other areas. Filters for example aren't very easy to implement.

Therefor I suggest we take a look at some other bundles for pagination.

https://github.com/whiteoctober/Pagerfanta
https://github.com/beberlei/porpaginas

I have read something about a filter implementation for KnpPaginator bundle which includes using https://github.com/lexik/LexikFormFilterBundle . We might want to check that out aswell

**Comment by bjorvack** [comment]
@StijnVrolijk has there been any decision about what bundle to use?

**Comment by StijnVrolijk** [comment]
@bjorvack nope, take your pick
