### ISSUE TITLE
Upgrade to Symfony 3.x

### ISSUE THREAD

**Issue by StijnVrolijk** [sumocoders/Framework#149]
Since tests are failing because Twig deprecated a bunch of features used in Symfony 2.8, I think it's time we upgrade Symfony

**Comment by jonasdekeukelaere** [comment]
Ready in 6.0.0-dev branch

**Comment by ohvitorino** [comment]
I've tested the 6.0.0-dev branch. I found one problem and fixed it. Other than that, I didn't find any other problems yet.
Example bundle works as expected. I created a user and logged in with it so the Multi User Bundle also seems to be working properly. Tests also ran successfully.
Any other functionalities I should be able to test without writing much code?

**Comment by jonasdekeukelaere** [comment]
I think other stuff needs custom code, so should be fine I think.

**Comment by jonasdekeukelaere** [comment]
@ohvitorino maybe merge master changes into the dev branch?

**Comment by ohvitorino** [comment]
@jonasdekeukelaere I merged master into the dev branch, also updated to symfony 3.3.4.

**Comment by jonasdekeukelaere** [comment]
👍
