### ISSUE TITLE
[frontend] integrate Select2 in favor of our own implementation

### ISSUE THREAD

**Issue by tijsverkoyen** [sumocoders/Framework#15]
See https://select2.github.io

**Comment by WouterSioen** [comment]
Weren't you against such plugins?

**Comment by tijsverkoyen** [comment]
Not for multiple selects, I am against replacing default behaviour (unless it sucks, like the multiple-select.

**Comment by WouterSioen** [comment]
Alright, I thought you'd replace all dropdowns with this.

You can just use `'expanded' => true` on a multiselect box, and it changes in a list of checkboxes. In most cases, this is enough. Only for loads of data, this select2 should be used.
