### ISSUE TITLE
Add gedmo/doctrine-extensions by default

### ISSUE THREAD

**Issue by carakas** [sumocoders/Framework#161]
It ads a number of things to help so maybe it is an idea to add it by default to the framework

**Comment by bjorvack** [comment]
@carakas do I provide a default config for all extensions

**Comment by carakas** [comment]
maybe only the ones we actually use?

**Comment by bjorvack** [comment]
That would be Translatable, Loggable and Sluggable

**Comment by carakas** [comment]
do you actually use translatable? I think that implementation is a bit rubbish

**Comment by bjorvack** [comment]
Not really. I'll create a config for Loggable an Sluggable then. Do you use other parts of this bundle @carakas

**Comment by carakas** [comment]
isn't there also a blame thing?

**Comment by bjorvack** [comment]
There is Tree, Translatable, Sluggable, Timestampable, Blameable, Loggable, Sortable, Translator, SoftDeleteable, Uploadable, References, ReferenceIntegrity and IpTraceable
https://github.com/Atlantic18/DoctrineExtensions

**Comment by carakas** [comment]
SoftDeleteable, Blamable and Sortable maybe?

**Comment by bjorvack** [comment]
@StijnVrolijk @ohvitorino which extensions do you use?

**Comment by ohvitorino** [comment]
Those three seem the must useful. Sluggable also looks interesting, but I never used it.
