### ISSUE TITLE
Variable "css" does not exist.

### ISSUE THREAD

**Issue by StijnVrolijk** [sumocoders/Framework#179]
in the default mail template, there's a variable to parse CSS but when it's not filled an error is thrown

https://github.com/sumocoders/Framework/blob/master/app/Resources/views/mails/default_email.html.twig#L7

https://github.com/sumocoders/Framework/blob/master/app/Resources/views/mails/default_email.html.twig#L12

Proposed solution: `{% if css %}{{ css|raw }}{% endif %}`

**Comment by jonasdekeukelaere** [comment]
I think you should always add the css in the head as well for some email clients. But @tijsverkoyen will be able to confirm that.

**Comment by tijsverkoyen** [comment]
I think this was added to make the styling work in more email-clients.

**Comment by StijnVrolijk** [comment]
The problem is it now requires the 'css' variable to be set with every email you send. Couldn't this be implemented as a fallback? Or we could just place some default CSS in the header and have an optional css variable to complement this?
