### ISSUE TITLE
Travis - Trusty as default Linux

### ISSUE THREAD

**Issue by ohvitorino** [sumocoders/Framework#184]
'Trusty as default Linux is coming' as you can read on this blog post [travis blog](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default).

We should upgrade our travis configuration to use this image.

**Comment by tijsverkoyen** [comment]
@ohvitorino If I read the blogpost, I don't think we have to change anything:
> Or in other words, projects without an explicit dist YAML key in their .travis.yml file will be routed to Trusty instead of Precise.

**Comment by ohvitorino** [comment]
Well, my comment is not very clear. I mean that we need to adjust our travis configuration otherwise the travis setup/deploy will fail like on this build:
https://travis-ci.org/sumocoders/Framework/builds/257201854?utm_source=github_status&utm_medium=notification
