### ISSUE TITLE
Clean up composer.json

### ISSUE THREAD

**Issue by WouterSioen** [sumocoders/Framework#25]
I believe that

        "redexperts/errbit-bundle": "dev-master",
        "emgiezet/errbit-php": "1.0.*@dev",

could be removed. Maybe some other dependencies too?

**Comment by tijsverkoyen** [comment]
Fixed in https://github.com/sumocoders/Framework/commit/ff83bf8b12b4dcbfddeb37338afaef2806f9adeb
