### ISSUE TITLE
Iconen fixen

### ISSUE THREAD

**Issue by tijsverkoyen** [sumocoders/Framework#71]
Artboad moet 100x100 en zonder kleuren zijn.

**Comment by tijsverkoyen** [comment]
Is een issue in redesign-2015 branch

**Comment by tijsverkoyen** [comment]
De branch is ondertussen gemerged naar de master.

**Comment by DaanDD** [comment]
Op master zie ik momenteel geen problemen met de iconen. Alle iconen zijn ook 100x100 en in 1 kleur.
