### ISSUE TITLE
Framework config is put in CoreBundle

### ISSUE THREAD

**Issue by WouterSioen** [sumocoders/Framework#74]
The config for the framework should be put in app/config/config.yml, not in the FrameworkCoreBundle.

**Comment by tijsverkoyen** [comment]
Which configuration-items should be moved into app/config/config.yml? Because I like that the defaults are in the FrameworkCoreBundle, it keeps the app/config/config.yml-file clean

**Comment by WouterSioen** [comment]
I think most of this should be in the app/config/config.yml file.

app/config/config.yml => used to  configure the framework
config.yml in a bundle => used to configure this specific bundle

I think everything in the FrameworkCoreBundle config file is used to configure the framework, not this specific bundle.

If I have to change a framework setting, I check the app/config/config.yml file and it's confusing that the relevant settings can't be found in there.

**Comment by tijsverkoyen** [comment]
But the FrameworkCoreBundle is used to glue the bundles together and configures a lot of stuff specific for the framework.
I can agree that some of the items should be moved, but the purpose of the FrameworkCoreBundle is to fix a much as possible for you instead of bloating other files.

**Comment by WouterSioen** [comment]
The Symfony documentation and all almost other applications build on Symfony put the framework, twig, doctrine,... configuration items in the app/config/config.yml file. I think putting it in a bundle makes it harder for developers to use the Framework, since it's breaking this convention, and thus makes changing configuration items confusing. (It does this at least for me)

**Comment by WouterSioen** [comment]
To be sure, I've checked some other projects using Symfony Full stack and they all do it this way:

* https://github.com/Sylius/Sylius/blob/master/app/config/config.yml
* https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config.yml
* https://github.com/sonata-project/sandbox/blob/2.3/app/config/config.yml
* https://github.com/symfony-cmf/standard-edition/blob/master/app/config/config.yml
* ...

**Comment by tijsverkoyen** [comment]
Meuh, I don't like it ;-) @sumocoders/php-team any opinions?

**Comment by carakas** [comment]
I understand both views
It doesn't really matter for me, but maybe if we would break the convention you could just point to the bundle config on the place where it normally should be

**Comment by jonasdekeukelaere** [comment]
Hmm, hard one...
It's mostly all core (framework related) stuff, and that's why there is the CoreBundle, to but core stuff in. But then again the app/config/config.yml will become mostly obsolete.
Maybe put the general stuff, like options that are likely to change in the general config file and the not so common one in the core bundle.

**Comment by tijsverkoyen** [comment]
Ok, then it should move to the app/config/config.yml
