### ISSUE TITLE
Better datepicker

### ISSUE THREAD

**Issue by tijsverkoyen** [sumocoders/Framework#92]
Use https://github.com/eternicode/bootstrap-datepicker in favor of the jquery-ui datepicker. As it is a lot more accessible and better for easy selecting years/months...

**Comment by WouterSioen** [comment]
:+1:

**Comment by tijsverkoyen** [comment]
@carakas isn't this something that has been developed in EDC?

**Comment by carakas** [comment]
Yes, but some things didn't work entirely, Bjorn fixed them over there.
There are some other things from EDC that should be pull requested aswell.
Ill see if I can have a look at these things next week
